# Site settings
title: System-on-Chip Design & Verification
author: Michele Lynch
  name: Edmond Wilkinson
  email: G00414989@atu.ie
description: "A blog."

# Build settings
remote_theme: jekyll/minima
